M48
; DRILL file {KiCad (6.0.1)} date Fri Oct 20 16:16:59 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-20T16:16:59-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X150.368Y-69.088
X150.622Y-117.348
X208.788Y-69.342
X209.042Y-117.348
T0
M30
